"""Scan all skill directories and produce a JSON detail map for the dashboard."""
import os, json, glob

BASE = r"E:\AI_Workspace"

# Map known skill dirname -> real directory path
SKILL_ROOTS = [
    ".claude/skills",
    "superpowers/skills",
    "anthropics-skills/skills",
    "dbskill/skills",
    "OpenCLI/skills",
    "planning-with-files/skills",
    r"redNoteExpressApp\agent-skills\skills",
    r"redNoteExpressApp\taste-skill\skills",
    r"redNoteExpressApp\last30days-skill\skills",
    r"ui-ux-pro-max-skill\.claude\skills",
]

# Also scan standalone skill dirs at root level
STANDALONE = [
    "guizang-social-card-skill",
    "channel-strategist",
    "blogger-distiller",
    "baoyu-xhs-images",
]

def scan_dir(dirpath):
    """Return {files:[str], subdirs:[str], totalFiles:int, hasSkillMd:bool, excerpt:str}"""
    info = {"files": [], "subdirs": [], "totalFiles": 0, "hasSkillMd": False, "excerpt": ""}
    if not os.path.isdir(dirpath):
        return info
    try:
        entries = sorted(os.listdir(dirpath))
    except:
        return info

    file_count = 0
    for e in entries:
        ep = os.path.join(dirpath, e)
        if os.path.isfile(ep):
            info["files"].append(e)
            file_count += 1
        elif os.path.isdir(ep):
            info["subdirs"].append(e)
            # count nested files (shallow to avoid slowness)
            try:
                file_count += len([x for x in os.listdir(ep) if os.path.isfile(os.path.join(ep, x))])
            except:
                pass

    info["totalFiles"] = file_count

    # Read SKILL.md excerpt (first 500 chars)
    md_path = os.path.join(dirpath, "SKILL.md")
    if os.path.isfile(md_path):
        info["hasSkillMd"] = True
        try:
            with open(md_path, "r", encoding="utf-8") as f:
                content = f.read(2000)
            info["excerpt"] = content
        except:
            pass
    return info

def main():
    result = {}
    for root in SKILL_ROOTS:
        root_path = os.path.join(BASE, root)
        if not os.path.isdir(root_path):
            continue
        for name in sorted(os.listdir(root_path)):
            dirpath = os.path.join(root_path, name)
            if not os.path.isdir(dirpath):
                continue
            # Build key: use base name
            key = name
            # For dbskill/OpenCLI/agent-skills/taste/uiux, prefix to avoid collisions
            if root.startswith("dbskill"):
                key = f"dbskill/{name}"
            elif root.startswith("OpenCLI"):
                key = f"OpenCLI/{name}"
            elif root.startswith("redNoteExpressApp\\agent-skills"):
                key = f"agent-skills/{name}"
            elif root.startswith("redNoteExpressApp\\taste-skill"):
                key = f"taste/{name}"
            elif root.startswith("ui-ux"):
                key = f"uiux/{name}"

            result[key] = scan_dir(dirpath)
            result[key]["path"] = os.path.relpath(dirpath, BASE).replace("\\", "/")

    for name in STANDALONE:
        dirpath = os.path.join(BASE, name)
        if os.path.isdir(dirpath):
            result[name] = scan_dir(dirpath)
            result[name]["path"] = os.path.relpath(dirpath, BASE).replace("\\", "/")

    # Write JS file
    outpath = os.path.join(BASE, "scripts", "skill-details.js")
    with open(outpath, "w", encoding="utf-8") as f:
        f.write("// Auto-generated skill details - DO NOT EDIT\n")
        f.write("// Generated by scripts/scan_details.py\n")
        f.write("const SKILL_DETAILS = ")
        json.dump(result, f, ensure_ascii=False, indent=2)
        f.write(";\n")
    print(f"Wrote {len(result)} skills to {outpath}")

if __name__ == "__main__":
    main()
